### ISSUE TITLE
Error running: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by GJY-Git** [meelgroup/bosphorus#32]
Dear Mr Soos，
      I need your help. I have installed "bosphorus" on my computer before and it can be used normally, but when I install "bosphorus" on a server platform, I use a "test.anf" file that has been verified on my computer When the server platform was running, a "Segmentation fault (core dumped)" error occurred.

**Comment by msoos** [comment]
Hi,

Can you please run it under valgrind when it segfaults? Also, what server
are you running it on? If you want to compile one place and copy the
executable to run another place, you need to compile it statically, on a
virtual machine that has exactly the same libc and kernel version as the
server. Then copy that binary over. Otherwise you must compile on the
server itself to run on the server.

Good luck,

Mate

**Comment by msoos** [comment]
Hi,

Unfortunately, this is not reproducible so I can't fix :( Closing.
