### ISSUE TITLE
 If the Bosporus has executable file in Windows system?

### ISSUE THREAD

**Issue by zfx-code** [meelgroup/bosphorus#36]
Dear msoos
The Bosporus helped me a lot.(I only use it to convert ANF to CNF, and solve the CNF is faster than ANF2CNF)
But I mainly use Windows system, this main:
1. get ANF in Windows system;
2. send ANF to Linux system and convert to CNF;
3. send CNF to Windows or Linux systems.
It's a bit of a hassle.
So I wang to know if the Bosporus has executable file in Windows system?
Such as bosporus.exe...
Or it only can run in the Linux system?

Looking forward to your reply!
Thank you.

**Comment by msoos** [comment]
Hi,

It is likely possible, but difficult to build Bosphorus and its dependencies on Windows. Unfortunately, I don't have the time to figure it out. However, you can try to figure it out, though given what you wrote above, it seems like you may not be an expert Windows developer.

Instead, I suggest using the Windows Subsystem for Linux, where it maybe quite easy to build Bosphorus. Then you can run your executable in Windows, in a PowerShell that essentially runs Linux. See here: https://www.howtogeek.com/744328/how-to-install-the-windows-subsystem-for-linux-on-windows-11/ You can then google for "Windows Subsystem for Linux" and find how to build Linux executable such as Bosphorus on your Windows machine. This way, you could build and run Bosphorus from Windows.

Otherwise, I suggest installing a Virtual Machine manager, such as VirtualBox, in Windows. There, you can share disk with Windows and Linux, so you don't have to send the file -- just fire up your Linux VM, and then run the Bosphorus executable there. It will automatically appear in Windows.

I hope this helped,

Mate
